server {
    listen 3002;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index admin.html index.html;
        try_files $uri $uri/ /admin.html /index.html;
    }
}
